services:
  _defaults:
    public: true

  Ashiso\Security\Domain\Repositories\EnterpriseRepository:
    class: Ashiso\Security\Infrastructure\InMemory\InMemoryEnterpriseRepository

  Ashiso\Security\Domain\Repositories\ModuleRepository:
    class: Ashiso\Security\Infrastructure\InMemory\InMemoryModuleRepository

  Ashiso\Security\Domain\Repositories\UserRepository:
    class: Ashiso\Security\Infrastructure\InMemory\InMemoryUserRepository

  Ashiso\Security\Domain\Repositories\MemberRepository:
    class: Ashiso\Security\Infrastructure\InMemory\InMemoryMemberRepository

  Ashiso\Security\Domain\Gateways\AuthenticationGateway:
    class: Ashiso\Security\Infrastructure\InMemory\InMemoryAuthenticationGateway

  Ashiso\Security\Application\AuthorizationChecker:
    class: Ashiso\Security\Application\AuthorizationChecker
    autowire: true
