services:
  _defaults:
    public: true

  Doctrine\ORM\EntityManagerInterface:
    synthetic: true

  Addworking\Security\Domain\Repositories\EnterpriseRepository:
    class: Addworking\Security\Infrastructure\Doctrine\Repositories\DoctrineEnterpriseRepository
    autowire: true

  Addworking\Security\Domain\Repositories\ModuleRepository:
    class: Addworking\Security\Infrastructure\Doctrine\Repositories\DoctrineModuleRepository
    autowire: true

  Addworking\Security\Domain\Repositories\UserRepository:
    class: Addworking\Security\Infrastructure\Doctrine\Repositories\DoctrineUserRepository
    autowire: true

  Addworking\Security\Domain\Repositories\MemberRepository:
    class: Addworking\Security\Infrastructure\Doctrine\Repositories\DoctrineMemberRepository
    autowire: true

  Addworking\Security\Domain\Gateways\AuthenticationGateway:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryAuthenticationGateway
    autowire: true

  Addworking\Security\Application\AuthorizationChecker:
    class: Addworking\Security\Application\AuthorizationChecker
    autowire: true
