services:
  _defaults:
    public: true

  Addworking\Security\Domain\Repositories\EnterpriseRepository:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryEnterpriseRepository

  Addworking\Security\Domain\Repositories\ModuleRepository:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryModuleRepository

  Addworking\Security\Domain\Repositories\UserRepository:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryUserRepository

  Addworking\Security\Domain\Repositories\MemberRepository:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryMemberRepository

  Addworking\Security\Domain\Gateways\AuthenticationGateway:
    class: Addworking\Security\Infrastructure\InMemory\InMemoryAuthenticationGateway

  Addworking\Security\Application\Services\AuthorizationChecker:
    class: Addworking\Security\Application\Services\AuthorizationChecker
    autowire: true
